---
driver:
  name: vagrant

provisioner:
  name: ansible_playbook
  hosts: test-kitchen
  requirements_path: requirements.yml
  ansible_verbose: false
  ansible_verbosity: 2
  ansible_diff: true
  ansible_extra_flags: <%= ENV['ANSIBLE_EXTRA_FLAGS'] %>

platforms:
  - name: ubuntu-14.04
  - name: centos-7.2

suites:
  - name: node0
    driver:
      customize:
        memory: 1024
      network:
        - ["private_network", { ip: "172.29.129.11" }]
  - name: node1
    driver:
      network:
        - ["private_network", { ip: "172.29.129.12" }]
