---

- name: Create payload json file for adding service api config to kong
  template: src=service_api.json.j2 dest=/tmp/service_api.json
  delegate_to: 127.0.0.1
  become: false

- name: Add service api object to kong
  uri: 
    url:    "{{ kong_admin_api_url|default('http://localhost:8001') }}/apis/"
    method: POST
    body:   "{{ lookup('file','/tmp/service_api.json') }}"
    status_code: "201"
    body_format: json
  register: api
  when: not kong_service_api.name in apis.json.data|map(attribute='name')

- debug: msg="{{ kong_service_api.name }} api object already exists - ({{ apis.json.data|map(attribute='name')|join(',') }})"
  when: kong_service_api.name in apis.json.data|map(attribute='name')

- name: Update service api object configured in kong
  uri: 
    url:    "{{ kong_admin_api_url|default('http://localhost:8001') }}/apis/{{ kong_service_api.name }}"
    method: PATCH
    body:   "{{ lookup('file','/tmp/service_api.json') }}"
    status_code: "200"
    body_format: json
  register: api
  when: kong_service_api.name in apis.json.data|map(attribute='name')

#- debug: var=api
