---

- name: Verify kong admin api available
  uri: url="{{ kong_admin_api_url|default('http://localhost:8001') }}"

# Get list of consumer objects
- name: Get list of kong consumer objects
  uri:
    url: "{{ kong_admin_api_url }}/consumers"
  register: consumers

- set_fact: _cmd=add

- set_fact: _cmd=delete
  when: kong_delete_consumer_obj
  
- name: Kong Consumer Object Config
  include: consumer_{{ _cmd }}.yml
