---

- name: Get list of route objects configured in kong associated with service
  uri:
    url: "{{ kong_admin_api_url|default('http://localhost:8001') }}/services/{{ kong_service_config.service.name }}/routes"
    status_code: "200,404"
  register: all_routes

#- debug: var=all_routes

- name: Get ids of routes no longer associated to kong service - {{ kong_service_config.service.name }}
  template: src=unmatched_route_ids.j2 dest=/tmp/unmatched_route_ids.result
  delegate_to: 127.0.0.1
  become: false

- name: Set ids of routes to delete
  set_fact: unmatched_route_ids="{{ lookup('file', '/tmp/unmatched_route_ids.result') }}"

- debug: var=unmatched_route_ids

- name: Delete route object not associated to kong service object - {{ kong_service_config.service.name }}
  uri:
    url:    "{{ kong_admin_api_url|default('http://localhost:8001') }}/routes/{{ item }}"
    method: DELETE
    status_code: "204,404"
  register: route_del
  with_items: "{{ unmatched_route_ids.split(' ') }}"
  when: unmatched_route_ids != ''

#- debug: var=route_del
