---

# Debian
- name: Download kong deb package | Debian
  get_url: url="{{ kong_deb_pkg_url }}" dest=/var/tmp validate_certs=no
  when: ansible_os_family|lower == 'debian'

- name: Install kong prerequisites (Debian/Ubuntu only)
  apt: 
    name: "{{ item }}"
    update_cache: yes
    state: present
  with_items: "{{ kong_prereqs }}"
  when: ansible_os_family|lower == 'debian'

- name: Install kong extra prerequisites (Debian/Ubuntu only) | v0.8.x or earlier
  apt: 
    name: "{{ item }}"
    update_cache: yes
    state: present
  with_items: [ netcat, dnsmasq ]
  when: ansible_os_family|lower == 'debian' and kong_version|version_compare('0.9.0', '<')

- name: Install kong | Debian
  apt:
    deb:   "/var/tmp/kong-{{ kong_version }}.{{ ansible_distribution_release }}_all.deb"
    state: present
  when: ansible_os_family|lower == 'debian'

# RedHat
- name: Download kong rpm package | RedHat
  get_url: url="{{ kong_rpm_pkg_url }}" dest=/var/tmp validate_certs=no
  when: ansible_os_family|lower == 'redhat'

- name: Install kong | RedHat
  yum: 
    name: "/var/tmp/kong-{{ kong_version }}.el7.noarch.rpm"
    disable_gpg_check: yes
    state: present
  when: ansible_os_family|lower == 'redhat'

- name: Ensure kong nginx working dir has appropriate permissions
  file:
    path:  "{{ kong_nginx_working_dir }}"
    owner: root
    group: root
    mode:  0777     # vanilla install gives mode=0777 but could it be mode=0755?

- name: Create logrotate config for kong logs
  template:
    src:  logrotate.j2
    dest: /etc/logrotate.d/kong
    owner: root
    group: root
    mode: 0644


- name: Kong Server Config & Start
  include: "server-{{ kong_major_minor_version }}.x.yml"
