---

# When there are routes associated to a service, the routes need to be deleted
# before attempting to delete the service. Outcome of doing otherwise is:
#   HTTP/1.1 400 Bad Request
#   {"fields":{"@referenced_by":"routes"},"name":"foreign key violation","code":4,"message":"an existing 'routes' entity references this 'services' entity"}
#
- include: route_delete.yml

- name: Delete service object configured in kong
  uri:
    url:    "{{ kong_admin_api_url|default('http://localhost:8001') }}/services/{{ kong_service_config.service.name }}"
    method: DELETE
    status_code: "204,404"
  register: service
  when: kong_service_config.service.name in services.json.data|map(attribute='name')

#- debug: var=service

# Note: Deleting a service object also deletes plugin objects configured for it
