---

##-------------------
##  v0.9.x or later
##-------------------
- name: Create kong config file | v0.9.x or later
  template: 
    src:  "0.9.x-kong.conf.j2"
    dest: "{{ kong_conf_dir }}/kong.conf"
    owner: root
    group: root
    mode:  0644
  #when: kong_version|version_compare('0.9.0', '>=')
  notify: 
    - Validate kong config
    - Restart kong

- name: Create kong custom nginx config file | v0.9.x or later
  template: 
    src:  custom-nginx.template.j2
    dest: "{{ kong_conf_dir }}/custom-nginx.template"
    owner: root
    group: root
    mode:  0644
  #when: kong_version|version_compare('0.9.0', '>=')
  notify: 
    - Validate kong config
    - Reload kong

- name: Check kong health status | v0.9.x or later
  shell: kong health || true
  environment:
    PATH: "{{ ansible_env.PATH }}:/usr/local/bin"
  register: health
  #when: kong_version|version_compare('0.9.0', '>=')

- name: Set kong run status | v0.9.x or later
  set_fact: 
    run_status: down
  when: health.stderr.find('Kong is not running') != -1
  #when: kong_version|version_compare('0.9.0', '>=') and health.stderr.find('Kong is not running') != -1

- debug: var=health
  when: kong_version|version_compare('0.9.0', '>=')

- name: Start kong | v0.9.x or earlier
  shell: >
      ulimit -n "{{ kong_max_files_limit }}" && \
        kong start --conf {{ kong_conf_dir }}/kong.conf --nginx-conf {{ kong_conf_dir }}/custom-nginx.template
  environment:
    PATH: "{{ ansible_env.PATH }}:/usr/local/bin"
  when: run_status|default("up") == "down"
  #when: kong_version|version_compare('0.9.0', '>=') and run_status|default("up") == "down"
  register: start

- debug: var=start.stdout_lines

#- pause: minutes=60
