---

- name: Validate kong config
  shell: >
      kong check {{ kong_conf_dir }}/kong.conf
  environment:
    PATH: "{{ ansible_env.PATH }}:/usr/local/bin"
  when: kong_version|version_compare('0.9.0', '>=')

- name: Reload kong
  command: service kong reload
  environment:
    PATH: "{{ ansible_env.PATH }}:/usr/local/bin"

- name: Restart kong
  command: service kong restart
